(DPS-3203) Customer SSO versioning
livechat/livechat-public-docs pull request #1055
Opened 2021-11-18 14:00 UTC by jakubsikora

# ❗️ Feature branch / Deploy Preview

We suggest to name your branch with `feature/`, for example, `feature/DPS-2947`. See below notifications from **Netlify** about the url.

# 🚀 Links

Replace the placeholder data in links 👇

- [Jira](https://livechatinc.atlassian.net/browse/DPS-3203)

# 📓 Description
Add support for versions inside redoc docs.

2021-12-07 10:54 UTC, ale-kacperczyk commented on src/pages/authorization/customer-accounts-api/index.mdx
> +apiVersion: "3.3"
This is supposed to be 1.0

2021-12-07 10:54 UTC, ale-kacperczyk commented on src/pages/authorization/customer-accounts-api/v2.0/index.mdx
> +apiVersion: "2.0"
2.0 is stable

2021-12-07 10:55 UTC, ale-kacperczyk commented on src/constant/index.js
> +    ALL_VERSIONS: ["3.3", "2.0"],
```suggestion
    ALL_VERSIONS: ["1.0", "2.0"],
```

2021-12-07 10:55 UTC, ale-kacperczyk commented on src/constant/index.js
> +    LEGACY_VERSIONS: ["2.0"],
```suggestion
    LEGACY_VERSIONS: ["1.0"],
```

2021-12-07 10:55 UTC, ale-kacperczyk commented on src/constant/index.js
> +    STABLE_VERSION: "3.3",
```suggestion
    STABLE_VERSION: "2.0",
```

2021-12-09 08:38 UTC, arturfracala requested changes
Nice work 👊 Needs some polishing

2021-12-09 08:38 UTC, arturfracala commented on src/components/Page/index.js
> +                          style={{
I believe we don't use inline styles anymore 🙈

2021-12-09 08:38 UTC, arturfracala commented on src/utils/index.js
> +  console.log(category);
Please remove this

2021-12-09 08:44 UTC, ale-kacperczyk approved these changes

2021-12-09 08:56 UTC, arturfracala approved these changes

2021-12-09 08:57 UTC, merged