(NO-DPS) Bug fix - customer SDK isn't displayed on sidebar
livechat/livechat-public-docs pull request #1068
Opened 2021-12-06 14:15 UTC by arturfracala

# ❗️ Feature branch / Deploy Preview

We suggest to name your branch with `feature/`, for example, `feature/DPS-2947`. See below notifications from **Netlify** about the url.

# 🚀 Links

Replace the placeholder data in links 👇

- [Jira](https://livechatinc.atlassian.net/browse/XXX-XXX)

# 📓 Description

2021-12-06 14:20 UTC, jakubsikora requested changes

2021-12-06 14:20 UTC, jakubsikora commented on src/utils/index.js
> +export const getStableVersion = (category) => {
What about `data-reporting` https://github.com/livechat/livechat-public-docs/blob/master/src/constant/index.js#L16 ?

2021-12-06 17:06 UTC, jakubsikora approved these changes

2021-12-07 11:19 UTC, ale-kacperczyk commented
@arturfracala, feel free to merge this today when you have time :)

2021-12-07 15:34 UTC, merged