(DPS-3416) Right-side sidebar is missing method names & script refactor
livechat/livechat-public-docs pull request #1076
Opened 2021-12-15 15:12 UTC by dominikslawkowski

# ❗️ Feature branch / Deploy Preview

We suggest to name your branch with `feature/`, for example, `feature/DPS-2947`. See below notifications from **Netlify** about the url.

# 🚀 Links

Replace the placeholder data in links 👇

- [Jira](https://livechatinc.atlassian.net/browse/DPS-3416)

# 📓 Description

2021-12-16 08:30 UTC, arturfracala requested changes
Nice work! 😊

2021-12-16 08:30 UTC, arturfracala commented on scripts/buildArticles.js
> +            console.log("currentPrefix", currentPrefix);
Delete this line, please

2021-12-20 07:46 UTC, arturfracala approved these changes

2021-12-23 08:07 UTC, jakubsikora approved these changes

2021-12-23 08:14 UTC, merged