(DED-591) Create a new navbar in docs
livechat/livechat-public-docs pull request #1354
Opened 2023-04-11 12:28 UTC by arturfracala

# Deploy preview

Scroll down to the checks section for the link to the deploy preview of your branch.

# Links

Link your Jira ticket.

- [Jira](https://livechatinc.atlassian.net/browse/DED-591)

# Description

# Review and release

Apply changes and resolve conflicts. Once the described functionality lands on prod, let us know on #platform-docs-releases that your PR is ready for release. We will **merge** and **publish** the changes.

2023-04-12 10:24 UTC, AdalbertusLiver requested changes

2023-04-12 10:24 UTC, AdalbertusLiver commented on src/components/core/Navbar/Platform.js
> +          ))}
missing `key` prop when mapping

2023-04-12 10:24 UTC, AdalbertusLiver commented on src/components/core/Navbar/Platform.js
> +          ))}
missing `key` prop when mapping

2023-04-12 10:24 UTC, AdalbertusLiver commented on src/components/core/Navbar/Resources.js
> +          ))}
missing `key` prop when mapping

2023-04-12 10:24 UTC, AdalbertusLiver commented on src/components/core/Navbar/Resources.js
> +          ))}
missing `key` prop when mapping

2023-04-12 15:02 UTC, SamborGornicz approved these changes

2023-04-13 13:49 UTC, AdalbertusLiver approved these changes

2023-04-13 13:57 UTC, merged