API-13095: bot templates and bot auth
livechat/livechat-public-docs pull request #1447
Opened 2023-12-11 12:47 UTC by litwinow

# Links

- [API-13095](https://livechatinc.atlassian.net/browse/API-13095)
- [API-13083](https://livechatinc.atlassian.net/browse/API-13083)

# Description

Add bot template mgmt and bot auth methods.

2023-12-13 09:12 UTC, zuczkows commented on src/pages/management/configuration-api/v3.6/index.mdx
> +| `id`                            | Yes      | `string` | Bot Template ID
```suggestion
| `id`                            | Yes      | `string` | Bot ID                                                                                                                                                                                                                                                                                  |
```

2023-12-13 10:52 UTC, kacperf531 requested changes

2023-12-13 10:52 UTC, kacperf531 commented on src/pages/management/configuration-api/v3.6/index.mdx
> +| `owner_client_id`                        | Yes      | `string`   | Required only when authorizing via [PATs](/authorization/authorizing-api-calls/#personal-access-tokens). When you provide this par
check the link. Perhaps it should point to /authorization/agent-authorization#personal-access-tokens

2023-12-13 10:52 UTC, kacperf531 commented on payloads/management/v3.6/configuration-api/responses/bots/createBotTemplate.json
> +  "id": "5c9871d5372c824cbf22d860a707a578"
`secret` is missing
also add to `create_bot` resp snippet

2023-12-18 10:48 UTC, kacperf531 approved these changes

2023-12-18 13:09 UTC, ale-kacperczyk approved these changes

2023-12-18 13:34 UTC, merged