API-7030: translation properties
livechat/livechat-public-docs pull request #750
Opened 2020-08-24 10:26 UTC by lpmichalik

## 🚀 Links

- [Feature branch](https://developers.labs.livechat.com/docs/feature/API-7030-translation-props)
- [Jira](https://livechatinc.atlassian.net/browse/API-7030)

## 📓 Description

## ✅ Checklist (for API docs)

- Changelog
- API versions
- Web & RTM
- **Table:** Available methods/webhooks/pushes
- **Table:** Specifics

For more guidelines, see [Updating API docs](https://livechatinc.atlassian.net/wiki/spaces/PAT/pages/761529400/Updating+API+docs).

## 👷 Type of change (remove not needed)

### Content

- New content
  
### Features (for the website)

- New feature

2020-08-25 09:53 UTC, ale-kacperczyk requested changes

2020-08-25 09:53 UTC, ale-kacperczyk commented on content/messaging/references/default-properties/index.mdx
> +Specifies source language code.
```suggestion
Specifies the source language code.
```

2020-08-25 09:53 UTC, ale-kacperczyk commented on content/messaging/references/default-properties/index.mdx
> +Specifies target language code.
```suggestion
Specifies the target language code.
```

2020-08-25 09:53 UTC, ale-kacperczyk commented on content/messaging/references/default-properties/index.mdx
> +Message text in target language.
```suggestion
Contains message text in the target language.
```

2020-08-25 13:23 UTC, bkubiak commented
I can't find the update, what am I doing wrong?
https://developers.labs.livechat.com/docs/messaging/references/default-properties/#available-properties

2020-08-25 13:24 UTC, lpmichalik commented
https://developers.labs.livechat.com/docs/feature/API-7030-translation-props/messaging/references/default-properties/#header

2020-08-26 06:48 UTC, ale-kacperczyk commented on content/messaging/references/default-properties/index.mdx
> +			  "target_message": "Witaj Świecie!"
indentation too big

2020-08-26 08:27 UTC, bkubiak approved these changes

2020-08-26 13:59 UTC, ale-kacperczyk approved these changes

2020-09-01 10:04 UTC, merged