add notifications.incoming_message_for_focused_chat agent property
livechat/livechat-public-docs pull request #751
Opened 2020-08-24 12:27 UTC by lpmichalik

## 🚀 Links

- [Feature branch](https://developers.labs.livechat.com/docs/feature/API-6905-notifications-incoming_message_for_focused_chat)
- [Jira](https://livechatinc.atlassian.net/browse/API-6905)

## 📓 Description

## ✅ Checklist (for API docs)

- Changelog
- API versions
- Web & RTM
- **Table:** Available methods/webhooks/pushes
- **Table:** Specifics

For more guidelines, see [Updating API docs](https://livechatinc.atlassian.net/wiki/spaces/PAT/pages/761529400/Updating+API+docs).

## 👷 Type of change (remove not needed)

### Content

- New content
  
### Features (for the website)

- New feature

2020-08-25 10:04 UTC, ale-kacperczyk requested changes

2020-08-25 10:04 UTC, ale-kacperczyk commented on content/management/changelog/index.mdx
> +- New notification type [`incoming_message_for_focused_chat`](/management/configuration-api/v3.2/#create-agent).
```suggestion
- In [**Create Agent**](/management/configuration-api/v3.3/#create-agent), there's a new notification option, `incoming_message_for_focused_chat`.
```

2020-08-25 12:58 UTC, litwinow approved these changes
LGTM

2020-08-26 06:46 UTC, ale-kacperczyk approved these changes

2020-09-01 09:19 UTC, merged