(DPS-2266) Improvements for Rating component
livechat/livechat-public-docs pull request #752
Opened 2020-08-24 15:36 UTC by ale-kacperczyk

## 🚀 Links

- [Feature branch](https://developers.labs.livechat.com/docs/feature/dps-2266)
- [Jira](https://livechatinc.atlassian.net/browse/DPS-2266)

## 📓 Description
Added a modal with an iframe displaying a Google Form.

## 👷 Type of change (remove not needed)

### Features (for the website)

- New feature
- Breaking change

2020-08-26 12:51 UTC, jakubsikora requested changes
Good work, few suggestions.

2020-08-26 12:51 UTC, jakubsikora commented on src/components/core/Rating/modal.js
> +  background-color: "white";
```suggestion
  background-color: #FFFFFF;
```

2020-08-26 12:51 UTC, jakubsikora commented on src/components/core/Rating/modal.js
> +  opacity: ${(props) => props.isLoading ? "1.0" : "0"};
```suggestion
  opacity: ${(props) => props.isLoading ? 1 : 0};
```

2020-08-26 12:51 UTC, jakubsikora commented on src/components/core/Rating/modal.js
> +          : null}
```suggestion
        {isLoading && <LoaderWrapper isLoading={isLoading}><Loader size="large" /></LoaderWrapper>}
```

2020-08-26 13:04 UTC, ale-kacperczyk commented on src/components/core/Rating/modal.js
> +  opacity: ${(props) => props.isLoading ? "1.0" : "0"};
deleted opacity

2020-08-27 06:57 UTC, jakubsikora approved these changes
Nicely done!

2020-08-27 10:14 UTC, merged