API-7198: Fix params in v3.3 customer configuration endpoints
livechat/livechat-public-docs pull request #754
Opened 2020-09-03 06:59 UTC by litwinow

## 🚀 Links

- [Feature branch](https://developers.labs.livechat.com/docs/feature/API-7198-configuration-endpoints-fixes)
- [Jira](https://livechatinc.atlassian.net/browse/API-7198)

## 📓 Description
* whitelist -> allowed
* prechat_survey -> prechat_form
* group_id optional in get_dynamic_configuration

## ✅ Checklist (for API docs)

- Changelog
- API versions
- Web & RTM
- **Table:** Available methods/webhooks/pushes
- **Table:** Specifics

For more guidelines, see [Updating API docs](https://livechatinc.atlassian.net/wiki/spaces/PAT/pages/761529400/Updating+API+docs).

## 👷 Type of change (remove not needed)
Update of existing content in dev preview version.

### Content

- Proofreading/content fixes
  
### Features (for the website)

- Breaking change

2020-09-22 11:08 UTC, ale-kacperczyk requested changes

2020-09-22 11:08 UTC, ale-kacperczyk commented on content/messaging/customer-chat-api/v3.1/index.mdx
> +| `form`    |                                                                                                                        |
```suggestion
| `form`    |  The `form` object                                                                                                                    |
```

2020-09-22 11:08 UTC, ale-kacperczyk commented on content/messaging/customer-chat-api/v3.1/rtm-reference/index.mdx
> +| `form`    |                                                                                                                        |
```suggestion
| `form`    | The `form` object                                                                                                                     |
```

2020-09-22 11:08 UTC, ale-kacperczyk commented on content/messaging/customer-chat-api/v3.1/index.mdx
> +| `form`    |                                                                                                                        |
I'd add it because it looks empty

2020-09-23 08:45 UTC, ale-kacperczyk approved these changes

2020-09-25 10:54 UTC, litwinow commented
@ale-kacperczyk , one more change XD

2020-09-25 11:04 UTC, ale-kacperczyk requested changes

2020-09-25 11:04 UTC, ale-kacperczyk commented on content/messaging/customer-chat-api/v3.3/index.mdx
> +| `domain_whitelisted`    | `bool`     | Specifies if `url` is configured as a trusted domain (configurable in the Agent Application).
```suggestion
| `domain_allowed`    | `bool`     | Specifies if `url` is configured as a trusted domain (configurable in the Agent Application).                                                                             |
```

2020-09-25 11:31 UTC, ale-kacperczyk approved these changes

2020-10-01 13:26 UTC, merged