API-7592: activate -> resume chat
livechat/livechat-public-docs pull request #790
Opened 2020-11-09 11:43 UTC by lpmichalik

start/resume_chat: `active`

## 🚀 Links

- [Feature branch](https://developers.labs.livechat.com/docs/feature/API-7592-resume-and-offline-thread)
- [Jira](https://livechatinc.atlassian.net/browse/API-7592)

## 📓 Description

## ✅ Checklist (for API docs)

- Changelog
- API versions
- Web & RTM
- **Table:** Available methods/webhooks/pushes
- **Table:** Specifics

For more guidelines, see [Updating API docs](https://livechatinc.atlassian.net/wiki/spaces/PAT/pages/761529400/Updating+API+docs).

## 👷 Type of change (remove not needed)

### Content

- New content
- Proofreading/content fixes
  
### Features (for the website)

- New feature
- Bug fix
- Breaking change

2020-11-09 14:07 UTC, ale-kacperczyk requested changes

2020-11-09 14:07 UTC, ale-kacperczyk commented on content/messaging/agent-chat-api/v3.3/rtm-reference/index.mdx
> +| `active`                 | No       | `bool`     | When set to `false` creates an inactive thread; default: `true`.                                         |
```suggestion
| `active`                 | No       | `bool`     | When set to `false`, creates an inactive thread; default: `true`.                                         |
```

2020-11-09 14:07 UTC, ale-kacperczyk commented on content/messaging/agent-chat-api/v3.3/rtm-reference/index.mdx
> +| `active`                 | No       | `bool`     | When set to false, creates new inactive thread. Default `true`.                                          |
```suggestion
| `active`                 | No       | `bool`     | When set to `false`, creates an inactive thread. Default `true`.                                          |
```

2020-11-09 14:07 UTC, ale-kacperczyk commented on content/messaging/customer-chat-api/changelog/index.mdx
> +- The **Activate Chat** has been renamed to **Resume Chat** ([Web](/messaging/customer-chat-api/v3.3/#resume-chat) & [RTM](/messaging/customer-chat-api/v3.3/rtm-reference/#resume-chat)).
```suggestion
- The **Activate Chat** method was renamed to **Resume Chat** ([Web](/messaging/customer-chat-api/v3.3/#resume-chat) & [RTM](/messaging/customer-chat-api/v3.3/rtm-reference/#resume-chat)).
```

2020-11-09 14:07 UTC, ale-kacperczyk commented on content/messaging/customer-chat-api/changelog/index.mdx
> +- The **Start Chat** ([Web](/messaging/agent-chat-api/v3.3/#start-chat) & [RTM](/messaging/customer-chat-api/v3.3/rtm-reference/#start-chat)) and **Resume Chat** ([Web](/messaging/customer-chat-api/v
```suggestion
- The **Start Chat** ([Web](/messaging/agent-chat-api/v3.3/#start-chat) & [RTM](/messaging/customer-chat-api/v3.3/rtm-reference/#start-chat)) and **Resume Chat** ([Web](/messaging/customer-chat-api/v3.3/#resume-chat) & [RTM](/messaging/customer-chat-api/v3.3/rtm-reference/#resume-chat)) methods have a new optional parameter, `active`.
```

2020-11-09 14:07 UTC, ale-kacperczyk commented on content/messaging/customer-chat-api/v3.3/index.mdx
> +| `active`                 | No       | `bool`    | When set to `false` creates an inactive thread; default: `true`.            |
```suggestion
| `active`                 | No       | `bool`    | When set to `false`, creates an inactive thread; default: `true`.            |
```

2020-11-09 14:07 UTC, ale-kacperczyk commented on content/messaging/customer-chat-api/v3.3/index.mdx
> +| `active`                 | No       | `bool`   | When set to `false` creates an inactive thread; default: `true`.           |
```suggestion
| `active`                 | No       | `bool`   | When set to `false`, creates an inactive thread; default: `true`.           |
```

2020-11-09 14:07 UTC, ale-kacperczyk commented on content/messaging/customer-chat-api/v3.3/rtm-reference/index.mdx
> +| `active`                 | No       | `bool`    | When set to `false` creates an inactive thread; default: `true`.            |
```suggestion
| `active`                 | No       | `bool`    | When set to `false`, creates an inactive thread; default: `true`.            |
```

2020-11-09 14:07 UTC, ale-kacperczyk commented on content/messaging/customer-chat-api/v3.3/rtm-reference/index.mdx
> +| `active`                 | No       | `bool`   | When set to `false` creates an inactive thread; default: `true`.           |
```suggestion
| `active`                 | No       | `bool`   | When set to `false`, creates an inactive thread; default: `true`.           |
```

2020-11-09 14:07 UTC, ale-kacperczyk commented on content/messaging/customer-chat-api/v3.3/rtm-reference/index.mdx
> +<!-- > **`resume_chat`** sample **request** with optional params
This is some legacy stuff that doesn't need to be updated. Feel free to delete it next time you come across it.

2020-11-09 14:07 UTC, ale-kacperczyk commented on content/messaging/agent-chat-api/v3.3/rtm-reference/index.mdx
> +<!-- > **`resume_chat`** sample **request** with optional params
This is some legacy stuff that doesn't need to be updated. Feel free to delete it next time you come across it.

2020-11-12 10:39 UTC, ale-kacperczyk commented on content/messaging/agent-chat-api/changelog/index.mdx
> +- The **Activate Chat** method has been renamed to **Resume Chat** ([Web](/messaging/agent-chat-api/v3.3/#resume-chat) & [RTM](/messaging/agent-chat-api/v3.3/rtm-reference/#resume-chat)).
```suggestion
- The **Activate Chat** method was renamed to **Resume Chat** ([Web](/messaging/agent-chat-api/v3.3/#resume-chat) & [RTM](/messaging/agent-chat-api/v3.3/rtm-reference/#resume-chat)).
```

2020-11-12 10:41 UTC, ale-kacperczyk approved these changes
LGTM 👍🏻

2020-11-12 10:41 UTC, ale-kacperczyk commented on content/messaging/agent-chat-api/changelog/index.mdx
> +- The **Activate Chat** method has been renamed to **Resume Chat** ([Web](/messaging/agent-chat-api/v3.3/#resume-chat) & [RTM](/messaging/agent-chat-api/v3.3/rtm-reference/#resume-chat)).
I missed it, sorry.

2020-11-12 14:15 UTC, bkubiak approved these changes

2020-11-30 12:13 UTC, merged