Additional info about user's EventsSeenUpTo in Start/ResumeChat and S…
livechat/livechat-public-docs pull request #816
Opened 2021-01-12 10:46 UTC by gluszczyk

…endEvent.

## 🚀 Links

- [Feature branch](https://developers.labs.livechat.com/docs/feature/API-7061-activate-chat-seen-events)
- [Jira](https://livechatinc.atlassian.net/browse/API-6987)

## 📓 Description

Start/ResumeChat - describes new behavior in v3.3
SendEvent - adds missing info

## 👷 Type of change (remove not needed)

### Content

- New content
- Proofreading/content fixes

2021-01-12 12:03 UTC, ale-kacperczyk requested changes

2021-01-12 12:03 UTC, ale-kacperczyk commented on content/messaging/agent-chat-api/index.mdx
> +Updates requester's `events_seen_up_to` as if they've seen all chat events.
+ Please, apply the same change in other documents.

2021-01-12 12:48 UTC, gluszczyk commented on content/messaging/agent-chat-api/changelog/index.mdx
> +- The **Start Chat** and **Activate Chat** methods now update requester's `events_seen_up_to` as if they've seen all chat events. Subsequent call to `mark_events_as_seen` can be skipped in these case
and now we have `the requester's` almost next to each other, kinda bothers me 😉

2021-01-12 13:14 UTC, ale-kacperczyk commented on content/messaging/agent-chat-api/changelog/index.mdx
> +- The **Start Chat** and **Activate Chat** methods now update requester's `events_seen_up_to` as if they've seen all chat events. Subsequent call to `mark_events_as_seen` can be skipped in these case
Well, what can I say? :D I believe we can compromise the style for the sake of clarity. 

How about?

> The **Start Chat** and **Activate Chat** methods now update the requester's `events_seen_up_to` as if all chat events were already seen by the requester.

2021-01-12 14:48 UTC, gluszczyk commented on content/messaging/agent-chat-api/changelog/index.mdx
> +- The **Start Chat** and **Activate Chat** methods now update requester's `events_seen_up_to` as if they've seen all chat events. Subsequent call to `mark_events_as_seen` can be skipped in these case
ok, that's an acceptable compromise :trollface:

2021-01-13 12:05 UTC, ale-kacperczyk approved these changes

2021-01-21 08:12 UTC, merged