API-7864: Document new filter
livechat/livechat-public-docs pull request #818
Opened 2021-01-12 11:47 UTC by Adimus11

## 🚀 Links

- [Feature branch](https://developers.labs.livechat.com/docs/feature/API-7864-document-new-flter-for-list-customers)
- [Jira](https://livechatinc.atlassian.net/browse/API-7864)

## 📓 Description

## ✅ Checklist (for API docs)

- Changelog
- API versions
- Web & RTM
- **Table:** Available methods/webhooks/pushes
- **Table:** Specifics

For more guidelines, see [Updating API docs](https://livechatinc.atlassian.net/wiki/spaces/PAT/pages/761529400/Updating+API+docs).

## 👷 Type of change (remove not needed)

### Content

- New content

2021-01-12 14:09 UTC, litwinow requested changes

2021-01-12 14:09 UTC, litwinow commented on content/messaging/agent-chat-api/changelog/index.mdx
> +  - has a new filter, `chat_group_ids`.
```suggestion
  - has new filters: `include_customers_without_chats` and `chat_group_ids`.
```

2021-01-12 14:09 UTC, litwinow commented on content/messaging/agent-chat-api/index.mdx
> +There's only one value allowed for a single filter.
merge with `<string_filter_type>`, there are too many stars already :(

2021-01-12 14:09 UTC, litwinow commented on content/messaging/agent-chat-api/index.mdx
> +There's only one value allowed for a single filter.
also, why it's described in v3.2?

2021-01-12 14:09 UTC, litwinow commented on content/messaging/agent-chat-api/v3.3/index.mdx
> +`<integer_filter_type>` can take the following values :
as above with the merge

2021-01-13 07:41 UTC, litwinow approved these changes

2021-01-13 07:41 UTC, litwinow commented on content/messaging/agent-chat-api/changelog/index.mdx
> +  - has a new filter, `include_customers_without_chats` and `chat_group_ids`.
```suggestion
  - has new filters: `include_customers_without_chats` and `chat_group_ids`.
```

2021-01-13 13:44 UTC, ale-kacperczyk commented on content/messaging/agent-chat-api/v3.3/index.mdx
> +`<integer_filter_type>` can take the following values :
```suggestion
`<integer_filter_type>` can take the following values:
```

2021-01-13 13:44 UTC, ale-kacperczyk commented on content/messaging/agent-chat-api/v3.3/rtm-reference/index.mdx
> +`<integer_filter_type>` can take the following values :
```suggestion
`<integer_filter_type>` can take the following values:
```

2021-01-14 14:40 UTC, litwinow approved these changes

2021-01-15 11:19 UTC, ale-kacperczyk approved these changes

2021-01-21 07:57 UTC, merged