AA-10652 - Add total chats report
livechat/livechat-public-docs pull request #820
Opened 2021-01-14 15:05 UTC by AlithAnar

## 🚀 Links

- [Feature branch](https://developers.labs.livechat.com/docs/feature/AA-10652-total-chats-report)
- [Jira](https://livechatinc.atlassian.net/browse/AA-10652)

## 📓 Description
Just adding total chats report to v3 reports. This PR should wait for https://github.com/livechat/livechat-public-docs/pull/819 to be merged

## 👷 Type of change (remove not needed)

### Content

- New content

2021-01-18 12:23 UTC, ale-kacperczyk requested changes

2021-01-18 12:23 UTC, ale-kacperczyk commented on content/data-reporting/changelog/index.mdx
> +- There's a new method, [**Total Chats**](/data-reporting/reports-api/#total_chats), which shows how many chats occurred during the specified period.
This entry should be logged under the new section for v3.3

> ## [v3.3] - Developer preview
> 
> ### Chats
> - There's a new method, [**Total Chats**](/data-reporting/reports-api/v3.3/#total-chats), which shows how many chats occurred during the specified period.

2021-01-18 12:44 UTC, ale-kacperczyk commented on content/data-reporting/changelog/index.mdx
> +- There's a new method, [**Total Chats**](/data-reporting/reports-api/#total_chats), which shows how many chats occurred during the specified period.
```suggestion
- There's a new method, [**Total Chats**](/data-reporting/reports-api/v3.3/#total_chats), which shows how many chats occurred during the specified period.
```

2021-01-18 12:50 UTC, AlithAnar commented on content/data-reporting/changelog/index.mdx
> +- There's a new method, [**Total Chats**](/data-reporting/reports-api/#total_chats), which shows how many chats occurred during the specified period.
Sorry, blue monday effect... fixing

2021-01-19 07:39 UTC, janowsiany approved these changes

2021-01-19 08:08 UTC, ale-kacperczyk approved these changes

2021-02-02 13:51 UTC, merged