Document missing routing properties
livechat/livechat-public-docs pull request #826
Opened 2021-01-26 09:08 UTC by litwinow

## 🚀 Links

- [Feature branch](https://developers.labs.livechat.com/docs/feature/API-7903-routing-props)
- [Jira](https://livechatinc.atlassian.net/browse/API-7903)

## 📓 Description
Document missing `routing` properties.

## ✅ Checklist (for API docs)
n/a

## 👷 Type of change (remove not needed)

### Content
- New content

2021-01-26 14:05 UTC, ale-kacperczyk requested changes
Could you please also update the code snippet for the routing namespace?

2021-01-26 14:05 UTC, ale-kacperczyk commented on content/messaging/references/default-properties/index.mdx
> +Specifies if the chat should not be routed to Bots during the automatic routing.
```suggestion
Specifies if the chat should not be routed to Bots during automatic routing.
```

2021-01-27 06:50 UTC, lpmichalik approved these changes

2021-01-27 07:50 UTC, litwinow commented
> Could you please also update the code snippet for the routing namespace?

done

2021-01-27 08:20 UTC, ale-kacperczyk approved these changes

2021-01-27 08:47 UTC, merged