Request email verification
livechat/livechat-public-docs pull request #871
Opened 2021-03-25 11:01 UTC by kogierman

## 🚀 Links

- [Feature branch](https://developers.labs.livechat.com/docs/feature/API-8156-antispam)
- [Jira](https://livechatinc.atlassian.net/browse/API-8156)

## 📓 Description

Document new endpoint for customer email verification

## ✅ Checklist (for API docs)

- Changelog
- API versions
- Web & RTM
- **Table:** Available methods/webhooks/pushes
- **Table:** Specifics

For more guidelines, see [Updating API docs](https://livechatinc.atlassian.net/wiki/spaces/PAT/pages/761529400/Updating+API+docs).

## 👷 Type of change (remove not needed)

### Content

- New content
  
### Features (for the website)

- New feature

2021-03-25 11:51 UTC, ale-kacperczyk requested changes

2021-03-25 11:51 UTC, ale-kacperczyk commented on content/messaging/customer-chat-api/changelog/index.mdx
> +- The **Customer** ([Web](/messaging/customer-chat-api/v3.3/#customer) & [RTM](/messaging/customer-chat-api/v3.3/rtm-reference/#customer)) data structure has new property: `email_verified`.
```suggestion
- The **Customer** ([Web](/messaging/customer-chat-api/v3.3/#customer) & [RTM](/messaging/customer-chat-api/v3.3/rtm-reference/#customer)) data structure has a new property, `email_verified`.
```

2021-03-25 11:51 UTC, ale-kacperczyk commented on content/messaging/customer-chat-api/changelog/index.mdx
> +- The **Customer** ([Web](/messaging/customer-chat-api/v3.3/#customer) & [RTM](/messaging/customer-chat-api/v3.3/rtm-reference/#customer)) data structure has new property: `email_verified`.
`,` instead of `:` because there's just one item

2021-03-25 11:51 UTC, ale-kacperczyk commented on content/messaging/customer-chat-api/v3.3/index.mdx
> +Requests verification of customer's email address by sending them verification email with link to confirm identity.
```suggestion
Requests the verification of the customer's email address by sending them a verification email with the identity confirmation link.
```

2021-03-25 11:51 UTC, ale-kacperczyk commented on content/messaging/customer-chat-api/v3.3/index.mdx
> +Once Customer verifies their identity, a POST callback is sent to URL provided in `callback_uri` request parameter with verified email in payload.
```suggestion
Once the customer verifies their identity, we'll send a POST callback to the URL you provided in the `callback_uri` request parameter. The callback will contain the verified email in the payload.
```

2021-03-25 11:51 UTC, ale-kacperczyk commented on content/messaging/customer-chat-api/v3.3/index.mdx
> +Identity verification mechanism has following restraints:
```suggestion
The identity verification mechanism has the following constraints:
```

2021-03-25 11:51 UTC, ale-kacperczyk commented on content/messaging/customer-chat-api/v3.3/index.mdx
> +- you can stack multiple verification requests, but only 10 least recently requested callbacks will be triggered
```suggestion
- We'll store multiple verification requests until a customer confirms their identity. Once the identity is confirmed, we'll send a callback only for the 10 most recent verification requests, not for all stored requests.
```

2021-03-25 11:51 UTC, ale-kacperczyk commented on content/messaging/customer-chat-api/v3.3/index.mdx
> +- after 7 days since last verification request, all callbacks are voided and will not be sent
```suggestion
- Seven days after the last verification request, all callbacks are voided and, as a result, won't be sent.
```

2021-03-25 11:51 UTC, ale-kacperczyk commented on content/messaging/customer-chat-api/v3.3/index.mdx
> +- if Customer already has their email verified, callback will be sent immediately without prompting Customer to verify again
```suggestion
- If a customer has already verified their email, the callback will be sent immediately, without prompting the customer to verify it again.
```

2021-03-25 11:51 UTC, ale-kacperczyk commented on content/messaging/customer-chat-api/v3.3/index.mdx
> +| `callback_uri` | Yes      | `string`  | URI to be called after Customer confirms their email address. Should return 200 code. There are no retries. |
```suggestion
| `callback_uri` | Yes      | `string`  | URI to be called after the customer confirms their email address. Should return 200 code. There are no retries. |
```

2021-03-25 11:51 UTC, ale-kacperczyk commented on content/messaging/customer-chat-api/v3.3/index.mdx
> +  'https://api.livechatinc.com/v3.2/customer/action/request_email_verification?license_id=<license_id>' \
```suggestion
  'https://api.livechatinc.com/v3.3/customer/action/request_email_verification?license_id=<license_id>' \
```

2021-03-25 11:51 UTC, ale-kacperczyk commented on content/messaging/customer-chat-api/v3.3/index.mdx
> +| `email_verified` | optional  |                                                                                           |
```suggestion
| `email_verified` | optional  | Specifies if the customer confirmed their email address. See [Request Email Verification](#request-email-verification).                                                                                         |
```

2021-03-25 11:51 UTC, ale-kacperczyk commented on content/messaging/customer-chat-api/v3.3/index.mdx
> +| `email_verified` | optional  |                                                                                           |
Please add the same note in other places and remember that the link might change

2021-03-25 11:51 UTC, ale-kacperczyk commented on content/messaging/customer-chat-api/changelog/index.mdx
> +- The **Customer** ([Web](/messaging/customer-chat-api/v3.3/#customer) & [RTM](/messaging/customer-chat-api/v3.3/rtm-reference/#customer)) data structure has new property: `email_verified`.
Shouldn't we repeat this entry in the Customer section in Changelog as well? 🤔

2021-03-25 11:51 UTC, ale-kacperczyk commented on content/messaging/customer-chat-api/changelog/index.mdx
> +- The **Customer** ([Web](/messaging/customer-chat-api/v3.3/#customer) & [RTM](/messaging/customer-chat-api/v3.3/rtm-reference/#customer)) data structure has new property: `email_verified`.
I believe we should also mention the new method

2021-03-25 12:58 UTC, ale-kacperczyk reviewed
It's not listed in the Available methods table. Apart from that, it's OK :)

2021-03-26 08:20 UTC, ale-kacperczyk commented on content/messaging/customer-chat-api/changelog/index.mdx
> +- There's a new method, [**Request Email Verification**](/messaging/customer-chat-api/v3.3/#request_email_verification).
```suggestion
- There's a new method, [**Request Email Verification**](/messaging/customer-chat-api/v3.3/#request-email-verification).
```

2021-03-26 08:22 UTC, ale-kacperczyk commented on content/messaging/customer-chat-api/v3.3/index.mdx
> +| **Other**         | [`check_goals`](#check-goals) [`get_form`](#get-form) [`get_predicted_agent`](#get-predicted-agent) [`get_url_info`](#get-url-info) [`mark_events_as_seen`](#mark-events-as-seen)
```suggestion
| **Other**         | [`check_goals`](#check-goals) [`get_form`](#get-form) [`get_predicted_agent`](#get-predicted-agent) [`get_url_info`](#get-url-info) [`mark_events_as_seen`](#mark-events-as-seen) [`accept_greeting`](#accept-greeting) [`cancel_greeting`](#cancel-greeting) [`request_email_verification`](#request-email-verification)                                                                                                                   |
```

2021-03-26 09:11 UTC, ale-kacperczyk approved these changes

2021-03-26 14:57 UTC, litwinow approved these changes

2021-03-26 15:04 UTC, merged