(DPS-2739) Migrate SideNav component
livechat/livechat-public-docs pull request #899
Opened 2021-04-22 15:13 UTC by arturfracala

## 🚀 Links

- [Feature branch](https://developers.labs.livechat.com/docs/feature/DPS-2739)
- [Jira](https://livechatinc.atlassian.net/browse/DPS-2739)

## 📓 Description

This is the initial version of migrated SideNav. Remember that there is still work to be done here. 

Missing steps: 

- [ ] Add support for h4 headings 
- [ ] Add missing slugs to nodes in headingsOffsetMap (crucial for active paths)
- [ ] Investigate why isExtended var doesn't work
- [ ] Resolve versioning problem
- [ ] Check working of the script that builds arrays of Articles 

<img width="1218" alt="Screenshot 2021-04-22 at 16 59 27" src="https://user-images.githubusercontent.com/28802251/115739227-0933b800-a38e-11eb-88ef-8e87f33cedcf.png">

## ✅ Checklist (for API docs)

- Changelog
- API versions
- Web & RTM
- **Table:** Available methods/webhooks/pushes
- **Table:** Specifics

For more guidelines, see [Updating API docs](https://livechatinc.atlassian.net/wiki/spaces/PAT/pages/761529400/Updating+API+docs).

## 👷 Type of change (remove not needed)

### Content

- New content
- Proofreading/content fixes
  
### Features (for the website)

- New feature
- Bug fix
- Breaking change

2021-04-27 06:39 UTC, jakubsikora requested changes
Wow, this looks complex, good work! I have few comments.

2021-04-27 06:39 UTC, jakubsikora commented on scripts/buildArticles.js
> +  categories.forEach((element) => {
Maybe `category` ?

```suggestion
  categories.forEach((category) => {
```

2021-04-27 06:39 UTC, jakubsikora commented on scripts/buildArticles.js
> +      const article = {};
Can we create a function which is formatting article so you could use it here and also in line 20. I know there are some differences there, but you should be able to make some generic.

2021-04-28 08:07 UTC, dominikslawkowski approved these changes
gj

2021-05-11 07:01 UTC, jakubsikora requested changes
Just one comment. The issue with memory leak will be investigated after we merge this.

2021-05-12 07:01 UTC, jakubsikora approved these changes

2021-05-12 07:02 UTC, merged