(DPS-2742) Migrate search component
livechat/livechat-public-docs pull request #904
Opened 2021-04-27 06:36 UTC by dominikslawkowski

## 🚀 Links

- [Feature branch](https://developers.labs.livechat.com/docs/feature/DPS-2742)
- [Jira](https://livechatinc.atlassian.net/browse/DPS-2742)

## 📓 Description

## ✅ Checklist (for API docs)

- Changelog
- API versions
- Web & RTM
- **Table:** Available methods/webhooks/pushes
- **Table:** Specifics

For more guidelines, see [Updating API docs](https://livechatinc.atlassian.net/wiki/spaces/PAT/pages/761529400/Updating+API+docs).

## 👷 Type of change (remove not needed)

### Content

- New content
- Proofreading/content fixes
  
### Features (for the website)

- New feature
- Bug fix
- Breaking change

2021-04-27 06:43 UTC, jakubsikora requested changes
Cool! Few comments.

2021-04-27 06:43 UTC, jakubsikora commented on src/components/core/SideNav/SideNav.js
> +import dynamic from "next/dynamic";
Do you need that ?

2021-04-27 06:43 UTC, jakubsikora commented on src/pages/_app.js
> +import "docsearch.js/dist/cdn/docsearch.min.css";
I dont think you need that. We are adding that in the head already, but if that works, perhaps you can remove inserting css in the seo.js component.

2021-04-27 06:43 UTC, jakubsikora commented on src/utils/index.js
> +    debug: true, //false,
should be false

2021-04-27 07:06 UTC, arturfracala approved these changes
Apart from the things that Jakub pointed out, it looks good to me. Nice job! 😄 🎉

2021-04-27 07:06 UTC, arturfracala commented on src/components/core/SideNav/SideNav.js
> +        <Link href="/" style={{ color: "inherit" }}>
It's missing `<a>` tag here. Look at documentation -> https://nextjs.org/docs/migrating/from-gatsby#links

2021-04-28 07:01 UTC, jakubsikora approved these changes

2021-04-28 07:01 UTC, merged