(DPS-2749) Check management content
livechat/livechat-public-docs pull request #908
Opened 2021-05-05 14:14 UTC by arturfracala

## 🚀 Links

- [Feature branch](https://developers.labs.livechat.com/docs/feature/DPS-2749)
- [Jira](https://livechatinc.atlassian.net/browse/DPS-2749)

## 📓 Description

## ✅ Checklist (for API docs)

- Changelog
- API versions
- Web & RTM
- **Table:** Available methods/webhooks/pushes
- **Table:** Specifics

For more guidelines, see [Updating API docs](https://livechatinc.atlassian.net/wiki/spaces/PAT/pages/761529400/Updating+API+docs).

## 👷 Type of change (remove not needed)

### Content

- New content
- Proofreading/content fixes
  
### Features (for the website)

- New feature
- Bug fix
- Breaking change

2021-05-11 06:56 UTC, jakubsikora requested changes
Few suggestions

2021-05-11 06:56 UTC, jakubsikora commented on src/pages/management/configuration-api/index.mdx
> +If you found a bug or a typo, you can let us know directly on GitHub. In case of any questions or feedback, don't hesitate to contact us at developers@livechat.com. We'll be happy to hear from you!
Cant we just use `<a href="mailto:developers@livechat.com">developers@livechat.com</a>` ?

2021-05-11 06:56 UTC, jakubsikora commented on src/pages/management/configuration-api/v3.4/index.mdx
> +If you found a bug or a typo, you can let us know directly on GitHub. In case of any questions or feedback, don't hesitate to contact us at developers@livechat.com. We'll be happy to hear from you!
Same here

2021-05-11 15:05 UTC, arturfracala commented on src/pages/management/limits/index.mdx
> +To find out more about resource limits and the possibilities to change them, <button style={{ background: 'none!important',
Link wasn't working here, so I changed the link to the button and added this css to keep the look. This site is hidden anyway, so I wouldn't care too much about it

2021-05-12 07:00 UTC, jakubsikora approved these changes

2021-05-12 07:00 UTC, merged